### ISSUE TITLE
update docs

### ISSUE THREAD

**Issue by yangnaihua** [aws/homebrew-tap#11]
Hi, i found this docs in difference languages is not the same version. 
 ex : install aws-cli, in other language is the old the function install.......ex: https://docs.aws.amazon.com/zh_cn/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html

**Comment by TheSriram** [comment]
Can you elaborate a bit more on the issue?

**Comment by yangnaihua** [comment]
Hi, i'am sorry, because i mix up two methods installer : [pip]  and [brew]. So you can close this Issues and thank you !

**Comment by TheSriram** [comment]
Cool, closing this issue.
