### ISSUE TITLE
Formula request: CloudFormation Lint

### ISSUE THREAD

**Issue by matsev** [aws/homebrew-tap#12]
CloudFormation Lint is a tool that 

> Validate CloudFormation yaml/json templates against the CloudFormation spec and additional checks

https://github.com/awslabs/cfn-python-lint

Related formula: [awscli](https://formulae.brew.sh/formula/awscli)
Related issue: https://github.com/awslabs/cfn-python-lint/issues/493

**Comment by jfuss** [comment]
@matsev Adding CFN Lint here would be cool. 

@kddejong and @TheSriram what are your thoughts? There might be a how do we share this across many teams and how can we keep this updated? I know @TheSriram and I have talked about how to automate SAM CLI part, maybe this could be extended to support other formulas in the tap.

**Comment by sthulb** [comment]
@luiseduardocolon Hey, can your team own this?

**Comment by TheDanBlanco** [comment]
@sthulb this looks like it's being handled by the cfn-lint folks. refer to #26

**Comment by sthulb** [comment]
Thanks for this @thedanblanco 🎉!

**Comment by bwagner5** [comment]
cfn-lint is now distributed in homebrew core: https://formulae.brew.sh/formula/cfn-lint

**Comment by hoffa** [comment]
Closing this as per comment above.
