### ISSUE TITLE
Issue when installation of AWS-SAM-CLI in MacOS Mojave (10.14)

### ISSUE THREAD

**Issue by selvaganeshi** [aws/homebrew-tap#14]
I tried to install SAM Cli from the following documentation.
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html

The last step is giving the following error. But I have the Python updated and has both the system python (2.7) and also Python3 installed.

> Selvaganeshs-MacBook-Pro:~ selva$ brew install aws-sam-cli
> ==> Installing aws-sam-cli from aws/tap
> ==> Downloading https://files.pythonhosted.org/packages/8f/29/a0cb402d1875d0b35aa7c99b644a75fc72762dce25bc4fce7d62e1b70825/aws-sam-cli-0.8.1.tar.gz
> Already downloaded: /Users/selva/Library/Caches/Homebrew/downloads/b87ebb48e5c20ee282fd4289ef9aabe2a660aa64fe6c9d407175f307f920a816--aws-sam-cli-0.8.1.tar.gz
> ==> Downloading https://files.pythonhosted.org/packages/4e/8b/75469c270ac544265f0020aa7c4ea925c5284b23e445cf3aa8b99f662690/virtualenv-16.1.0.tar.gz
> Already downloaded: /Users/selva/Library/Caches/Homebrew/downloads/bda8bcde19a275fd9c84a7ec957593976e90dfd0e461a87f5698f1d2286c0197--virtualenv-16.1.0.tar.gz
> ==> python3 -c import setuptools... --no-user-cfg install --prefix=/private/tmp/aws-sam-cli--homebrew-virtualenv-20181205-49570-i3buef/target --install-scripts=/private/tmp/aws-sam-cli--homebrew-virtualen
> Last 15 lines from /Users/selva/Library/Logs/Homebrew/aws-sam-cli/01.python3:
> -c
> import setuptools, tokenize
> __file__ = 'setup.py'
> exec(compile(getattr(tokenize, 'open', open)(__file__).read()
>   .replace('\r\n', '\n'), __file__, 'exec'))
> --no-user-cfg
> install
> --prefix=/private/tmp/aws-sam-cli--homebrew-virtualenv-20181205-49570-i3buef/target
> --install-scripts=/private/tmp/aws-sam-cli--homebrew-virtualenv-20181205-49570-i3buef/target/bin
> --single-version-externally-managed
> --record=installed.txt
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
> ModuleNotFoundError: No module named 'setuptools'
> 
> If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
> 
>  https://github.com/aws/homebrew-tap/issues

**Comment by jfuss** [comment]
@selvaganeshi See #7

**Comment by selvaganeshi** [comment]
Hi, Thank you!
I installed Python via Homebrew and after running the below script it was working!

brew link --overwrite pythonbrew postinstall python

**Comment by charithdesilva** [comment]
just doing ```brew postinstall python``` solved it for me.
