### ISSUE TITLE
First install of aws-sam-cli on Docker using linuxbrew/brew:2.5.8 fails

### ISSUE THREAD

**Issue by simon-olivier** [aws/homebrew-tap#146]
`sam` command returns a 127 error code after installation from brew on Docker.

**Reproduction step**
Create the following `Dockerfile`:
```Dockerfile
FROM linuxbrew/brew:2.5.8

RUN brew tap aws/tap &&\
    brew install aws-sam-cli &&\
    sam --version
```
Build the image:
```
docker build .
```

**Expected result**
Docker image is built correctly and the following log line is displayed:
```
SAM CLI, version 1.7.0
```

**Observed result**
Docker image build fails and the following log line is displayed
```
/bin/sh: 1: sam: not found
```

**Workaround**
Running the command `brew install aws-sam-cli` twice fix the issue

**Comment by peniakoff** [comment]
Agree with you @simon-olivier. Same problem for me. I was trying maniuplate users before install SAM, but nothing changed.

**Comment by hoffa** [comment]
Tried reproducing:

```bash
docker run -it -u linuxbrew linuxbrew/brew
```

Then in the container:

```bash
brew tap aws/tap
brew install aws-sam-cli
sam --version
```

Which works fine. Closing; assuming this was an issue with Homebrew or one of the dependencies (see e.g. https://github.com/aws/homebrew-tap/issues/189, https://github.com/aws/homebrew-tap/issues/130, https://github.com/aws/aws-sam-cli/issues/2320).
