### ISSUE TITLE
copilot-cli zsh completions not working

### ISSUE THREAD

**Issue by pbougie** [aws/homebrew-tap#152]
There are currently 2 versions of the Copilot CLI on Homebrew. This version (aws/tap/copilot-cli) and another (copilot). Both are version 1.0.0. Both are defective.

1. `aws/tap/copilot-cli` (this version)
- CLI works.
- Zsh completions do not work. Must manually install them.

2. `copilot`
- CLI does not work. Tried `copilot init` and command failed.
- Zsh completions work as expected.

Perhaps one version should be removed to prevent confusion.

**Comment by efekarakus** [comment]
Heya @pbougie 

Sent out:
1. https://github.com/aws/homebrew-tap/pull/153
2. https://github.com/Homebrew/homebrew-core/pull/66027

to fix both of these issues

**Comment by pbougie** [comment]
Thanks @efekarakus.
