### ISSUE TITLE
`aws-sam-cli` 1.16 bottles exist but are not referenced by tap

### ISSUE THREAD

**Issue by jfoy** [aws/homebrew-tap#162]
Seems like a `chore: bottles for 1.16.0` step may have been missed: https://github.com/aws/homebrew-tap/blob/9a9c296ff959f04023fe030ae9b79cdeb706097b/bottle-configs/aws-sam-cli.json#L7-L8

**Comment by mgrandis** [comment]
Thanks @jfoy!
This is fixed by PR #163 .
