### ISSUE TITLE
Running `brew tap aws/tap` on GitHub actions fails

### ISSUE THREAD

**Issue by ofhouse** [aws/homebrew-tap#182]
Hi,

currently all of my CI jobs on GitHub actions fail when they run `brew tap aws/tap`.
The issue first occurred as of today, so I guess something you changed here caused the failure?

Error log from GitHub Actions:
```
==> Tapping aws/tap
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/aws/homebrew-tap'...
Error: Invalid formula: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/aws/homebrew-tap/Formula/qldbshell.rb
formulae require at least a URL
Error: Cannot tap aws/tap: invalid syntax in tap!
Error: Process completed with exit code 1.
```

Reproduction repo here: https://github.com/ofhouse/repro-brew-tap-aws

**Comment by sriram-mv** [comment]
Thanks for the report! looks to be an erroneous formula. the last commit has now been reverted. Will double check on the formula on our end before re-introducing it.

**Comment by ofhouse** [comment]
Thanks, can confirm that reverting the commit resolved the issue!
