### ISSUE TITLE
aws-sam-cli package download failing on linux homebrew with 404 error

### ISSUE THREAD

**Issue by riznob** [aws/homebrew-tap#196]
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.22.0//aws-sam-cli-1.23.0.x86_64_linux.bottle.tar.gz
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.22.0//aws-sam-cli-1.23.0.x86_64_linux.bottle.tar.gz

It looks like the culprit might be here...
https://github.com/aws/homebrew-tap/blob/master/bottle-configs/aws-sam-cli.json#L8

**Comment by robertd** [comment]
Same behavior with 1.24.0... the url is wrong.

```sh
==> Upgrading aws/tap/aws-sam-cli 1.23.0 -> 1.24.0
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.23.0//aws-sam-cli-1.24.0.sierra.bottle.tar.gz

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "aws-sam-cli"
Download failed: https://github.com/aws/aws-sam-cli/releases/download/v1.23.0//aws-sam-cli-1.24.0.sierra.bottle.tar.gz
```

**Comment by mgrandis** [comment]
Sorry we were in the process of releasing the new 1.24 version.
This should be working now.

**Comment by robertd** [comment]
Thanks! It works now. You can also drop the `/` at the end of `root_url` too. Thanks for fixing this btw! 👍 

```sh
==> Downloading https://github.com/aws/aws-sam-cli/releases/download/v1.24.0//aws-sam-cli-1.24.0.sierra.bottle.tar.gz
```
