### ISSUE TITLE
Tap is currently broken in aws-sam-cli-nightly formula

### ISSUE THREAD

**Issue by shrug** [aws/homebrew-tap#325]
This commit: https://github.com/aws/homebrew-tap/commit/19ac09759f5ae7732a64fc4eb52a9c1ff4bac95a

Seems to have broken the tap:

`Error: Invalid formula: /usr/local/Homebrew/Library/Taps/aws/homebrew-tap/Formula/aws-sam-cli-nightly.rb
invalid attribute for formula 'aws/tap/aws-sam-cli-nightly': version (nil)
Error: Cannot tap aws/tap: invalid syntax in tap!`

**Comment by lorentzca** [comment]
It seems to have been fixed. 🤔 

https://github.com/aws/homebrew-tap/commit/b39b0528f804a5685053a14fe3c67315d008a6b1
