### ISSUE TITLE
`brew tap aws/sam` uses Github username/password auth which is deprecated (workaround included)

### ISSUE THREAD

**Issue by larenelg** [aws/homebrew-tap#347]
Following [this AWS SAM CLI tutorial](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html).

## Bug

Homebrew version:

```
Homebrew 3.5.1
Homebrew/homebrew-core (git revision dc1d562ae72; last commit 2022-06-08)
Homebrew/homebrew-cask (git revision f4c4c79e9c; last commit 2022-06-08)
```

When I run the following command:

```
brew tap aws/sam
```

I get the following error:

```
Cloning into '/usr/local/Homebrew/Library/Taps/aws/homebrew-sam'...
Username for 'https://github.com': larenelg
Password for 'https://larenelg@github.com': 
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/aws/homebrew-sam/'
Error: Failure while executing; `git clone https://github.com/aws/homebrew-sam /usr/local/Homebrew/Library/Taps/aws/homebrew-sam --origin=origin --template=` exited with 128.
```

As Github no longer supports username and password authentication on the command line.

I also tried updated my global github config with:

```
[url "git@github.com:"]
    insteadOf = "https://github.com/"
```

with no success.

## Expected

I expected the tap to clone the repo with `git@github.com:aws/homebrew-tap.git`, and to successfully add the tap.

## Workaround

My workaround was to manually clone the repo instead:

```
cd /usr/local/Homebrew/Library/Taps
mkdir aws && cd aws
git clone git@github.com:aws/homebrew-tap.git
```

**Comment by jfuss** [comment]
@larenelg You are running the wrong command. The tap is `aws/tap` not `aws/sam`. This is called out in step 5: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html#serverless-sam-cli-install-mac-sam-cli
