### ISSUE TITLE
sam cli not installing with brew

### ISSUE THREAD

**Issue by btsteve** [aws/homebrew-tap#7]
When I run brew install aws-cam-cli i am getting error. 

import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/aws-sam-cli--homebrew-virtualenv-20181114-49871-18qsdja/target
--install-scripts=/private/tmp/aws-sam-cli--homebrew-virtualenv-20181114-49871-18qsdja/target/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools'

**Comment by TheSriram** [comment]
Looks like your python3 might not be installed by homebrew. We just had one similar 
 issue that got resolved https://github.com/aws/homebrew-tap/issues/6.

Do take a look and let us know if it helps you.

**Comment by btsteve** [comment]
Ok that seems to have fixed it.
