### ISSUE TITLE
Upgrade to Python 3.8 Seems to Break Install

### ISSUE THREAD

**Issue by DanielFrank** [aws/homebrew-tap#81]
We do a CI/CD with homebrew install aws-sam-cli. The install stopped working about 12 hours ago. The upgrade to `python@3.8` seems to be the cause. If it's relevant the Docker instance we use has Python v3.5.3 and Python v2.7.13.

We get the following messaging when we install:
```
######################################################################## 100.0%
==> Pouring python@3.8-3.8.1.x86_64_linux.bottle.tar.gz
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.1/bin/python3 -s setup.py -
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.1/bin/python3 -s setup.py -
==> /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.1/bin/python3 -s setup.py -
==> Caveats
Python has been installed as
  /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/python3

You can install Python packages with
  /home/linuxbrew/.linuxbrew/opt/python@3.8/bin/pip3 install <package>
They will install into the site-package directory
  /home/linuxbrew/.linuxbrew/opt/python@3.8/lib/python3.8/site-packages

See: https://docs.brew.sh/Homebrew-and-Python

python@3.8 is keg-only, which means it was not symlinked into /home/linuxbrew/.linuxbrew,
because this is an alternate version of another formula.

If you need to have python@3.8 first in your PATH run:
  echo 'export PATH="/home/linuxbrew/.linuxbrew/opt/python@3.8/bin:$PATH"' >> ~/.bash_profile

For compilers to find python@3.8 you may need to set:
  export LDFLAGS="-L/home/linuxbrew/.linuxbrew/opt/python@3.8/lib"
  export CPPFLAGS="-I/home/linuxbrew/.linuxbrew/opt/python@3.8/include"

For pkg-config to find python@3.8 you may need to set:
  export PKG_CONFIG_PATH="/home/linuxbrew/.linuxbrew/opt/python@3.8/lib/pkgconfig"

==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.1: 3,747 files, 69.1MB
==> Installing aws/tap/aws-sam-cli
==> Downloading https://github.com/awslabs/aws-sam-cli/releases/download/v0.43.0
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
```
[...]
```
/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.43.0/libexec/bin/python3.7: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```
So the issue seem to be either that the paths/flags aren't correctly set because we're using a keg-only brew or that aws-sam-cli is expecting a version 3.7 of something and is not finding it.

(I'm running some experiments to get around this and will report/comment if I find anything).

**Comment by DanielFrank** [comment]
As an experiment, I
Brew installed `python@3.8`
Followed the instructions of PATH, LDFLAGS, CPPFLAGS and PK_CONFIG_PATH
Then tried to brew install aws-sam-cli.

I still get the
`/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.43.0/libexec/bin/python3.7: error while loading shared libraries: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory`
error so that seems to be the relevant issue.

**Comment by sriram-mv** [comment]
@DanielFrank are you attempting to build from source or is brew downloading bottles for you?

**Comment by DanielFrank** [comment]
@sriram-mv 
```brew tap aws/tap
brew install aws-sam-cli```
If this is what you're asking. It's also Homebrew for Linux if that's relevant.

Also note that the test build failed. https://travis-ci.org/aws/homebrew-tap/builds/652436241?utm_source=github_status&utm_medium=notification

**Comment by DanielFrank** [comment]
My workaround is that after installing Homebrew, I run `brew install python`. This installs python v3.7.  Since homebrew is treating the python v3.8 as a keg and ignoring it, it ends up installing sam with  v3.7. (At least I think that's what's happening.)

**Comment by sriram-mv** [comment]
rolled back to python3.7 for now, do let us know if this doesn't fix it.

**Comment by DanielFrank** [comment]
The rollback fixes it. I don't have to do my kluge for which I'm grateful. Am closing the ticket.
