### ISSUE TITLE
SAM CLI installation broken due to python version inconsistency

### ISSUE THREAD

**Issue by mmajis** [aws/homebrew-tap#93]
Looks like `brew install aws-sam-cli` resolves the python dependency to `python@3.8` but the bottled 0.53.0 comes with python3.7 executables.

This leads to the following error when trying to run `sam`: `dyld: Library not loaded: @executable_path/../.Python`

Maybe update the following line for python@3.7 or make a new bottle with python 3.8? https://github.com/aws/homebrew-tap/blob/cb8deccfed14358502f7e4e733c362a17b552fb6/Formula/aws-sam-cli.rb#L24

A workaround is to `brew install --build-from-source aws-sam-cli`.

**Comment by jfuss** [comment]
We updated the formula and generated new bottles. This should not happen anymore. Please reopen if it does.

**Comment by sbhatAcoustic** [comment]
installation still broken

**Comment by sque** [comment]
The problem still persists. I had to build from sources. Thanks for the workaround.
